fashionproject/fashionapp/urls.py
from django.urls import path
from.import views
app_name='fashionapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('fashion/<int:fashion_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

fashionproject/fashionproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fashionapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fashionproject/fashionapp/models.py
from django.db import models

# Create your models here.
class Fashion(models.Model):
    name=models.CharField(max_length=250)
    price=models.TextField()
    category=models.TextField()
    desc=models.TextField()
    img=models.ImageField(upload_to='photos')

    def __str__(self):
        return self.name

fashionproject/fashionapp/forms.py
from django import forms
from.models import Fashion
class FashionForm(forms.ModelForm):
    class Meta:
        model=Fashion
        fields=['name','price','category','desc','img']

fashionproject/fashionapp/views.py
from django.shortcuts import render, redirect
from.models import Fashion
from.forms import FashionForm
# Create your views here.
def index(request):
    fashion=Fashion.objects.all()
    return render(request,"index.html",{'fashion_list':fashion})

def detail(request,fashion_id):
    fashion=Fashion.objects.get(id=fashion_id)
    return render(request,"detail.html",{'fashion':fashion})

def add(request):
    if request.method=="POST":
        name = request.POST.get('name')
        price = request.POST.get('price')
        category = request.POST.get('category')
        desc = request.POST.get('desc')
        img = request.FILES['img']
        fashion=Fashion(name=name,price=price,category=category,desc=desc,img=img)
        fashion.save()
        return redirect('/')
    return render(request,"add.html")

def update(request,id):
    fashion = Fashion.objects.get(id=id)
    form = FashionForm(request.POST or None,request.FILES,instance=fashion)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"update.html",{'form':form,'fashion':fashion})

def delete(request,id):
    if request.method=="POST":
       fashion=Fashion.objects.get(id=id)
       fashion.delete()
       return redirect('/')
    return render(request,"delete.html")

fashionproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div style="padding:50px;line-height:200%;">
    <h3 style="color:green;">New Dress Details</h3>
    <input type="text" name="name" placeholder="Enter dress name"><br>
    <input type="text" name="price" placeholder="Enter price"><br>
    <input type="text" name="category" placeholder="Enter dress category"><br>
    <input type="text" name="desc" placeholder="Enter dress description"><br>
    <input type="file" name="img"><br>
    <input type="submit" style="color:red">
  </div>
</form>
{% endblock %}

fashionproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style="background-image:url({% static 'fashion2.jpg' %});
background-size:cover;background-position:top;background-repeat:no-repeat;">
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="">Trendz Collections</a>
    <a class="btn btn-danger" href="{% url 'fashionapp:add' %}">ADD</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

fashionproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h4 style="color:green;padding:10px;">Are you want to delete this dress<br></h4>
    <input type="submit" style="color:red">
</form>
{% endblock %}

fashionproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <img src="{{fashion.img.url}}" width="250" height="250">
        </div>
            <div class="col-md-6">
                 <h3 style="color:green;">{{fashion.name}}</h3>
                 <h4>{{fashion.price}}</h4>
                 <h5 style="color:blue;">{{fashion.category}}</h5>
                 <h6>{{fashion.desc}}</h6>
                 <a class="btn btn-warning" href="{% url 'fashionapp:update' fashion.id %}">UPDATE</a>
                 <a class="btn btn-danger" href="{% url 'fashionapp:delete' fashion.id %}">DELETE</a>
            </div>
    </div>
</div>
{% endblock %}

fashionproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
      {% for i in fashion_list %}
        <div class="col-md-2" style="padding:30px;">
            <div class="card" style="width:10rem;">
               <img src="{{i.img.url}}" class="card-img-top" alt="..." height="150">
                <div class="card-body" style="height:10rem;">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-title">{{i.price}}</p>
                    <a href="{% url 'fashionapp:detail' i.id %}"><b style="color:tomato;">VIEW DETAILS</b></a>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

fashionproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}